{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "task-app.fullname" . }}-backend
  labels:
    {{- include "task-app.backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "task-app.backend.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
